CREATE DATABASE trans_video;

USE trans_video;

CREATE TABLE BASE_INFO
(
  ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增ID' PRIMARY KEY ,
  KEY_WORD VARCHAR(64) NOT NULL DEFAULT '0' COMMENT '关键字',
  PAGE_NUM INT NOT NULL DEFAULT 0 COMMENT '页数',
  URL VARCHAR(100) NOT NULL DEFAULT '0' COMMENT 'YouTube地址',
  VIDEO_LINKS VARCHAR(4096) NOT NULL DEFAULT 0 COMMENT '视频链接',
  VALID INT NOT NULL DEFAULT 0 COMMENT '是否有效，0无效，1有效',
  PUBLISH_STATUS INT NOT NULL DEFAULT 0 COMMENT '发布状态，0未发布，1已发布',
  COLLECT_TIME TIMESTAMP  NOT NULL DEFAULT '1990-01-01 00:000:00' COMMENT '采集时间',
  PUBLISH_TIME TIMESTAMP  NOT NULL DEFAULT '1990-01-01 00:000:00' COMMENT '发布时间',
  CREATE_TIME TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP  COMMENT '创建时间',
  UPDATE_TIME TIMESTAMP  NOT NULL DEFAULT '1990-01-01 00:000:00' COMMENT '更新时间',
  INFO_HASH VARCHAR(64) NOT NULL DEFAULT '0' COMMENT 'hash',
  FETCH_STATUS INT NOT NULL DEFAULT 0 COMMENT '抓取状态：0初始状态，1抓取成功，2抓取失败',
  CRAW_STATUS INT NOT NULL DEFAULT 0 COMMENT '抓取状态',
  VIDEO_TITLE VARCHAR(1024) NOT NULL DEFAULT '0' COMMENT '视频名称',
  VIDEO_INFO VARCHAR(2048) NOT NULL DEFAULT '0' COMMENT '获取视频信息',
  VIDEO_ITEM_ID VARCHAR(64) NOT NULL DEFAULT '0' COMMENT 'topbuzz网视频ID',
  POST_STATUS INT NOT NULL DEFAULT 0 COMMENT 'post状态：0初始状态，1抓取成功，2抓取失败'

) ;

CREATE INDEX info_hash ON BASE_INFO(INFO_HASH);